// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD1SHyXMZnCHKV6UjV8R30gVKbeFyFWj4',
    appId: '1:1019506411549:web:e19ebec0132c8d04acdef4',
    messagingSenderId: '1019506411549',
    projectId: 'fir-mesure',
    authDomain: 'fir-mesure.firebaseapp.com',
    storageBucket: 'fir-mesure.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKCHKiQQbdrsvA3NFbLISuzzs0LOJgdY',
    appId: '1:1019506411549:android:05f3deb67aa8481eacdef4',
    messagingSenderId: '1019506411549',
    projectId: 'fir-mesure',
    storageBucket: 'fir-mesure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaj65qW6ub5QCj4cGXWrzvxqrQ-ieNNOU',
    appId: '1:1019506411549:ios:d8c8ce58e3aa8ef0acdef4',
    messagingSenderId: '1019506411549',
    projectId: 'fir-mesure',
    storageBucket: 'fir-mesure.firebasestorage.app',
    iosBundleId: 'com.mesure.clientMesureFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaj65qW6ub5QCj4cGXWrzvxqrQ-ieNNOU',
    appId: '1:1019506411549:ios:d8c8ce58e3aa8ef0acdef4',
    messagingSenderId: '1019506411549',
    projectId: 'fir-mesure',
    storageBucket: 'fir-mesure.firebasestorage.app',
    iosBundleId: 'com.mesure.clientMesureFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD1SHyXMZnCHKV6UjV8R30gVKbeFyFWj4',
    appId: '1:1019506411549:web:1e2486d3bc7fddfaacdef4',
    messagingSenderId: '1019506411549',
    projectId: 'fir-mesure',
    authDomain: 'fir-mesure.firebaseapp.com',
    storageBucket: 'fir-mesure.firebasestorage.app',
  );
}
